### ISSUE TITLE
pip install does not work (for me) on Windows 10

### ISSUE THREAD

**Issue by paul-bradbeer-adv** [cdpierse/transformers-interpret#12]
I'm getting an error when pip installing transformers-interpret

Collecting transformers-interpret
  Using cached https://files.pythonhosted.org/packages/20/5c/190decb08671a1b30a7686cb7b26609d28d07f11f1ee164f7374a2cb7f66/transformers-interpret-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\T2NPAU~1.BRA\AppData\Local\Temp\pip-install-7xovqegv\transformers-interpret\setup.py", line 6, in <module>
        long_description = fh.read()
      File "C:\Users\paul.bradbeer\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 5676: character maps to <undefined>

Code in setup.py assumes utf-8

with open("README.md", "r") as fh:
    long_description = fh.read()

If I change the file open to have encoding iso-8859-1 then it works

Is this down to something inside README.md or is it something on my local python env/system?

**Comment by paul-bradbeer-adv** [comment]
Duplicated
